server:
  port: 8081
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whwhdemo1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    username: root
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
  style: camelhump